package view;

import controller.*;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import model.CorsoUni;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author berrettis
 */
public class Corsi extends javax.swing.JFrame {

    public static GestoreApp G = new GestoreApp();
    private ArrayList<CorsoUni> corsi;

    /**
     * Creates new form Corsi
     */
    public Corsi(GestoreApp G) {
        this.G = G;
        this.corsi = G.getElencoCorsi();
        initComponents();
    }

    private void scriviFileCSV() {
        G.salvaCorsiFIle();
    }

    private void mostraNumeroCorsi() {
        int numeroCorsi = G.contaCorsi();
        jTextArea1.setText("Numero di Corsi: " + numeroCorsi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Salva");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aggiungi", "Modifica", "Elimina", "ContaCorsi" }));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setText("Modifica Corsi");
        jLabel1.setMaximumSize(new java.awt.Dimension(70, 46));
        jLabel1.setMinimumSize(new java.awt.Dimension(47, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String ch = ",";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String input = jTextArea1.getText();

        if (jComboBox1.getSelectedItem().equals("Aggiungi")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String[] data = input.split(ch);
                String codice = data[0];
                String nome = data[1];
                int durata = Integer.parseInt(data[2].substring(1, 2));
                String newLine = codice + "," + nome + "," + durata;

                CorsoUni nuovoCorso = new CorsoUni(codice, nome, durata);
                corsi.add(nuovoCorso);

                // Riscrivi l'ArrayList nel file CSV
                scriviFileCSV();
            }
        }

        if (jComboBox1.getSelectedItem().equals("Modifica")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String[] data = input.split(",");

                if (data.length < 3) {
                    throw new IllegalArgumentException("I dati inseriti non sono validi.");
                }

                String codiceDaModificare = data[0].trim();
                String nuovoNome = data[1].trim();
                int nuovaDurata = Integer.parseInt(data[2].trim());

                boolean trovato = false;

                // Cerca il corso e modifica i suoi dati
                for (int i = 0; i < corsi.size(); i++) {
                    CorsoUni corso = corsi.get(i);
                    if (corso.getCodice().equals(codiceDaModificare)) {
                        corso.setNome(nuovoNome);
                        corso.setDurata(nuovaDurata);
                        trovato = true;
                        break;
                    }
                }

                if (trovato) {
                    scriviFileCSV();
                } else {
                    throw new IllegalArgumentException("Corso non trovato con codice: " + codiceDaModificare);
                }
            }
        }

        if (jComboBox1.getSelectedItem().equals("Elimina")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String codiceDaEliminare = input.trim();

                boolean trovato = false;

                // Usa il ciclo for per trovare e rimuovere il corso
                for (int i = 0; i < corsi.size(); i++) {
                    CorsoUni corso = corsi.get(i);
                    if (corso.getCodice().equals(codiceDaEliminare)) {
                        corsi.remove(i);  // Rimuovi il corso
                        trovato = true;
                        break;  // Esci dal ciclo una volta che il corso è stato rimosso
                    }
                }

                if (trovato) {
                    scriviFileCSV();
                } else {
                    throw new IllegalArgumentException("Corso non trovato con codice: " + codiceDaEliminare);
                }
            }
           
        }
        if ((jComboBox1.getSelectedItem().equals("ContaCorsi"))) {
                mostraNumeroCorsi();
            }
    
    }//GEN-LAST:event_jButton1ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Corsi.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Corsi.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Corsi.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Corsi.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Corsi(G).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
