package view;

import controller.*;
import java.util.ArrayList;
import model.*;
import static view.Corsi.G;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author berrettis
 */
public class Discipline extends javax.swing.JFrame {

    public static GestoreApp G = new GestoreApp();
    private ArrayList<Disciplina> discipline;

    /**
     * Creates new form Discipline
     */
    public Discipline(GestoreApp G) {
        this.G = G;
        this.discipline = G.getElencoDiscipline();
        initComponents();
    }

    private void scriviFileCSV() {
        G.salvaCorsiFIle();
    }

    private void mostraNumeroDiscipline() {
        int numeroDiscipline = G.contaDiscipline();
        jTextArea1.setText("Numero di Corsi: " + numeroDiscipline);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aggiungi", "Modifica", "Elimina", "ContaDiscipline" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Salva");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setText("Modifica Discipline");
        jLabel1.setMaximumSize(new java.awt.Dimension(70, 46));
        jLabel1.setMinimumSize(new java.awt.Dimension(47, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed
    String ch = ",";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String input = jTextArea1.getText();

        if (jComboBox1.getSelectedItem().equals("Aggiungi")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String[] data = input.split(ch);
                String codice = data[0];
                String nome = data[1];
                int cfu = Integer.parseInt(data[2].substring(1, 2));
                String codiceCorso = data[3];
                ArrayList<Docente> docentii = new ArrayList<>();
                ArrayList<AppelloEsame> appello = new ArrayList<>();
                ArrayList<Studente> studenti = new ArrayList<>();

                Disciplina nuovaDisciplina = new Disciplina(codice, nome, cfu, codiceCorso, docentii, appello, studenti);
                discipline.add(nuovaDisciplina);

                // Riscrivi l'ArrayList nel file CSV
                scriviFileCSV();
            }

        }

        if (jComboBox1.getSelectedItem().equals("Modifica")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String[] data = input.split(",");

                if (data.length < 4) {
                    throw new IllegalArgumentException("I dati inseriti non sono validi.");
                }

                String codiceDaModificare = data[0].trim();
                String nuovoNome = data[1].trim();
                int nuovocfu = Integer.parseInt(data[2].substring(1, 2));
                String codiceCorso = data[3];
                ArrayList<Docente> newdocenti = new ArrayList<>();
                ArrayList<AppelloEsame> newappello = new ArrayList<>();
                ArrayList<Studente> newstudenti = new ArrayList<>();
                boolean trovato = false;

                // Cerca il corso e modifica i suoi dati
                for (int i = 0; i < discipline.size(); i++) {
                    Disciplina disciplina = discipline.get(i);
                    if (disciplina.getCodice().equals(codiceDaModificare)) {
                        disciplina.setNome(nuovoNome);
                        disciplina.setCFU(nuovocfu);
                        disciplina.setDocenti(newdocenti);
                        disciplina.setAppelli(newappello);
                        disciplina.setStudenti(newstudenti);
                        trovato = true;
                        break;
                    }
                }

                if (trovato) {
                    scriviFileCSV();
                } else {
                    throw new IllegalArgumentException("Disciplina non trovata con codice: " + codiceDaModificare);
                }
            }
        }

        if (jComboBox1.getSelectedItem().equals("Elimina")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String codiceDaEliminare = input.trim();

                boolean trovato = false;

                // Usa il ciclo for per trovare e rimuovere il corso
                for (int i = 0; i < discipline.size(); i++) {
                    Disciplina disciplina = discipline.get(i);
                    if (disciplina.getCodice().equals(codiceDaEliminare)) {
                        discipline.remove(i);  // Rimuovi il corso
                        trovato = true;
                        break;  // Esci dal ciclo una volta che il corso è stato rimosso
                    }
                }

                if (trovato) {
                    scriviFileCSV();
                } else {
                    throw new IllegalArgumentException("Disciplina non trovato con codice: " + codiceDaEliminare);
                }

            }
        }
        if ((jComboBox1.getSelectedItem().equals("ContaDiscipline"))) {
            mostraNumeroDiscipline();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Discipline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Discipline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Discipline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Discipline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Discipline(G).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
