package view;

import controller.*;
import java.util.ArrayList;
import model.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author berrettis
 */
public class Docenti extends javax.swing.JFrame {

    public static GestoreApp G = new GestoreApp();
    private ArrayList<Docente> docenti;

    /**
     * Creates new form Docenti
     */
    public Docenti(GestoreApp G) {
        this.G = G;
        this.docenti = G.getElencoDocenti();
        initComponents();
    }

    private void scriviFileCSV() {
        G.salvaCorsiFIle();
    }

    private void mostraNumeroDocenti() {
        int numeroDocenti = G.contaDocenti();
        jTextArea1.setText("Numero di Docenti: " + numeroDocenti);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aggiungi", "Modifica", "Elimina", "ContaDocenti" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Salva");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setText("Modifica Docenti");
        jLabel1.setMaximumSize(new java.awt.Dimension(70, 46));
        jLabel1.setMinimumSize(new java.awt.Dimension(47, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String ch = ",";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String input = jTextArea1.getText();

        if (jComboBox1.getSelectedItem().equals("Aggiungi")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String[] data = input.split(ch);

                String matricola = data[0];
                String nome = data[1];
                String cognome = data[2];
                String codiceDisciplina = data[3];
                String newLine = matricola + "," + nome + "," + cognome + "," + codiceDisciplina;

                Docente nuovoDocente = new Docente(matricola, nome, cognome, codiceDisciplina);
                docenti.add(nuovoDocente);
                scriviFileCSV();

            }
        }

        if (jComboBox1.getSelectedItem().equals("Modifica")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String[] data = input.split(",");

                if (data.length < 4) {
                    throw new IllegalArgumentException("I dati inseriti non sono validi.");
                }

                String matricolaDaModificare = data[0].trim();
                String nuovoNome = data[1].trim();
                String nuovoCognome = data[2].trim();
                String nuovoCodiceDisciplina = data[3].trim();

                boolean trovato = false;

                // Cerca il corso e modifica i suoi dati
                for (int i = 0; i < docenti.size(); i++) {
                    Docente docente = docenti.get(i);
                    if (docente.getMatricola().equals(matricolaDaModificare)) {
                        docente.setNome(nuovoNome);
                        docente.setCodiceDisciplina(nuovoCodiceDisciplina);
                        trovato = true;
                        break;
                    }
                }

                if (trovato) {
                    scriviFileCSV();
                } else {
                    throw new IllegalArgumentException("Docente non trovato con codice: " + matricolaDaModificare);
                }
            }
        }

        if (jComboBox1.getSelectedItem().equals("Elimina")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String matricolaDaEliminare = input.trim();

                boolean trovato = false;

                // Usa il ciclo for per trovare e rimuovere il corso
                for (int i = 0; i < docenti.size(); i++) {
                    Docente docente = docenti.get(i);
                    if (docente.getMatricola().equals(matricolaDaEliminare)) {
                        docenti.remove(i);  // Rimuovi il corso
                        trovato = true;
                        break;  // Esci dal ciclo una volta che il corso è stato rimosso
                    }
                }

                if (trovato) {
                    scriviFileCSV();
                } else {
                    throw new IllegalArgumentException("Docente non trovato con matricola: " + matricolaDaEliminare);
                }
            }
        }

        if ((jComboBox1.getSelectedItem().equals("ContaDocenti"))) {
            mostraNumeroDocenti();

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Docenti.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Docenti.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Docenti.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Docenti.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Docenti(G).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
