/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.*;
import java.util.ArrayList;
import model.*;
import static view.Docenti.G;

/**
 *
 * @author berrettis
 */
public class IscrizioneAppello extends javax.swing.JFrame {

    public static GestoreApp G = new GestoreApp();
    private ArrayList<Iscrizione> iscrizioni;

    /**
     * Creates new form IscrizioneAppello
     */
    public IscrizioneAppello(GestoreApp G) {
        this.G = G;
        this.iscrizioni = G.getElencoIscrizioni();
        initComponents();
    }

    private void scriviFileCSV() {
        G.salvaCorsiFIle();
    }

    private void mostraNumeroIscrizioni() {
        int numeroIscrizioni = G.contaIscrizioni();
        jTextArea1.setText("Numero di iscrizioni: " + numeroIscrizioni);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aggiungi", "Modifica", "Elimina", "ContaIscrizioni" }));

        jButton1.setText("Salva");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setText("Modifica Iscrizioni");
        jLabel1.setMaximumSize(new java.awt.Dimension(70, 46));
        jLabel1.setMinimumSize(new java.awt.Dimension(47, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String ch = ",";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String input = jTextArea1.getText();

        if (jComboBox1.getSelectedItem().equals("Aggiungi")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String[] data = input.split(ch);
                String idAppello = data[0];
                String matricolaStudente = data[1];

                String newLine = idAppello + "," + matricolaStudente;

                Iscrizione nuovaIscrizione = new Iscrizione(idAppello, matricolaStudente);
                iscrizioni.add(nuovaIscrizione);
                scriviFileCSV();

            }
        }
        if (jComboBox1.getSelectedItem().equals("Modifica")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String[] data = input.split(",");

                if (data.length < 2) {
                    throw new IllegalArgumentException("I dati inseriti non sono validi.");
                }

                String IDdaModificare = data[0].trim();
                String nuovamatricolaStudente = data[1].trim();

                boolean trovato = false;

                // Cerca il corso e modifica i suoi dati
                for (int i = 0; i < iscrizioni.size(); i++) {
                    Iscrizione iscrizione = iscrizioni.get(i);
                    if (iscrizione.getIdAppello().equals(IDdaModificare)) {
                        iscrizione.setMatricolaStudente(nuovamatricolaStudente);
                        trovato = true;
                        break;
                    }
                }

                if (trovato) {
                    scriviFileCSV();
                } else {
                    throw new IllegalArgumentException("Iscrizione non trovato con ID: " + IDdaModificare);
                }
            }
        }

        if (jComboBox1.getSelectedItem().equals("Elimina")) {
            if (input.equals("")) {
                throw new IllegalArgumentException();
            } else {
                String IDdaEliminare = input.trim();

                boolean trovato = false;

                // Usa il ciclo for per trovare e rimuovere il corso
                for (int i = 0; i < iscrizioni.size(); i++) {
                    Iscrizione iscrizione = iscrizioni.get(i);
                    if (iscrizione.getIdAppello().equals(IDdaEliminare)) {
                        iscrizioni.remove(i);  // Rimuovi il corso
                        trovato = true;
                        break;  // Esci dal ciclo una volta che il corso è stato rimosso
                    }
                }

                if (trovato) {
                    scriviFileCSV();
                } else {
                    throw new IllegalArgumentException("Iscrizione non trovato con ID: " + IDdaEliminare);
                }
            }
        }
        if ((jComboBox1.getSelectedItem().equals("ContaIscrizioni"))) {
            mostraNumeroIscrizioni();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IscrizioneAppello.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IscrizioneAppello.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IscrizioneAppello.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IscrizioneAppello.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IscrizioneAppello(G).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
