package view;

import controller.*;
import model.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author berrettis
 */
public class StartPage extends javax.swing.JFrame {

    public static GestoreApp G = new GestoreApp();

    /**
     * Creates new form AddUserForm
     */
    public StartPage() {
        initComponents();
        G.letturaAppelli("appelli.csv");
        G.letturaCorsi("corsi.csv");
        G.letturaDiscipline("discipline.csv");
        G.letturaDocenti("docenti.csv");
        G.letturaStudenti("studenti.csv");
        G.letturaIscrizioni("iscrizioni.csv");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextView = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        Navigation = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ModificaCorsi = new javax.swing.JMenuItem();
        VisualizzaCorsi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ModificaDiscipline = new javax.swing.JMenuItem();
        VisualizzaDiscipline = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ModificaDocenti = new javax.swing.JMenuItem();
        VisualizzaDocenti = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ModificaStudenti = new javax.swing.JMenuItem();
        VisualizzaStudenti = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ModificaAppelli = new javax.swing.JMenuItem();
        VisualizzaAppelli = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        ModificaIscrizioni = new javax.swing.JMenuItem();
        VisualizzaIscrizioni = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextView.setEditable(false);
        TextView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(TextView);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setText("Visualizza File");
        jLabel1.setMaximumSize(new java.awt.Dimension(70, 46));
        jLabel1.setMinimumSize(new java.awt.Dimension(47, 16));

        jMenu1.setText("Corsi");

        ModificaCorsi.setText("Modifica");
        ModificaCorsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaCorsiActionPerformed(evt);
            }
        });
        jMenu1.add(ModificaCorsi);

        VisualizzaCorsi.setText("Visualizza");
        VisualizzaCorsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizzaCorsiActionPerformed(evt);
            }
        });
        jMenu1.add(VisualizzaCorsi);

        Navigation.add(jMenu1);

        jMenu2.setText("Discipline");

        ModificaDiscipline.setText("Modifica");
        ModificaDiscipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaDisciplineActionPerformed(evt);
            }
        });
        jMenu2.add(ModificaDiscipline);

        VisualizzaDiscipline.setText("Visualizza");
        VisualizzaDiscipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizzaDisciplineActionPerformed(evt);
            }
        });
        jMenu2.add(VisualizzaDiscipline);

        Navigation.add(jMenu2);

        jMenu3.setText("Docenti");

        ModificaDocenti.setText("Modifica");
        ModificaDocenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaDocentiActionPerformed(evt);
            }
        });
        jMenu3.add(ModificaDocenti);

        VisualizzaDocenti.setText("Visualizza");
        VisualizzaDocenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizzaDocentiActionPerformed(evt);
            }
        });
        jMenu3.add(VisualizzaDocenti);

        Navigation.add(jMenu3);

        jMenu4.setText("Studenti");

        ModificaStudenti.setText("Modifica");
        ModificaStudenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaStudentiActionPerformed(evt);
            }
        });
        jMenu4.add(ModificaStudenti);

        VisualizzaStudenti.setText("Visualizza");
        VisualizzaStudenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizzaStudentiActionPerformed(evt);
            }
        });
        jMenu4.add(VisualizzaStudenti);

        Navigation.add(jMenu4);

        jMenu5.setText("Appelli");

        ModificaAppelli.setText("Modifica");
        ModificaAppelli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaAppelliActionPerformed(evt);
            }
        });
        jMenu5.add(ModificaAppelli);

        VisualizzaAppelli.setText("Visualizza");
        VisualizzaAppelli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizzaAppelliActionPerformed(evt);
            }
        });
        jMenu5.add(VisualizzaAppelli);

        Navigation.add(jMenu5);

        jMenu7.setText("IscrizioniAppelli");

        ModificaIscrizioni.setText("Modifica");
        ModificaIscrizioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaIscrizioniActionPerformed(evt);
            }
        });
        jMenu7.add(ModificaIscrizioni);

        VisualizzaIscrizioni.setText("Visualizza");
        VisualizzaIscrizioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizzaIscrizioniActionPerformed(evt);
            }
        });
        jMenu7.add(VisualizzaIscrizioni);

        Navigation.add(jMenu7);

        setJMenuBar(Navigation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificaCorsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaCorsiActionPerformed
        // Open Corsi
        Corsi c = new Corsi(G); // Create Corsi object
        c.setVisible(true);
    }//GEN-LAST:event_ModificaCorsiActionPerformed

    private void VisualizzaCorsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizzaCorsiActionPerformed
        this.TextView.setText(G.visualizzaCorsi());
    }//GEN-LAST:event_VisualizzaCorsiActionPerformed

    private void ModificaDisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaDisciplineActionPerformed
        Discipline d = new Discipline(G); // Create Corsi object
        d.setVisible(true);
    }//GEN-LAST:event_ModificaDisciplineActionPerformed

    private void VisualizzaDisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizzaDisciplineActionPerformed
        this.TextView.setText(G.visualizzaDiscipline());
    }//GEN-LAST:event_VisualizzaDisciplineActionPerformed

    private void ModificaDocentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaDocentiActionPerformed
        Docenti doc = new Docenti(G); // Create Corsi object
        doc.setVisible(true);
    }//GEN-LAST:event_ModificaDocentiActionPerformed

    private void VisualizzaDocentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizzaDocentiActionPerformed
        this.TextView.setText(G.visualizzaDocenti());
    }//GEN-LAST:event_VisualizzaDocentiActionPerformed

    private void VisualizzaStudentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizzaStudentiActionPerformed
        this.TextView.setText(G.visualizzaStudenti());
    }//GEN-LAST:event_VisualizzaStudentiActionPerformed

    private void VisualizzaAppelliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizzaAppelliActionPerformed
        this.TextView.setText(G.visualizzaAppelli());
    }//GEN-LAST:event_VisualizzaAppelliActionPerformed

    private void ModificaStudentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaStudentiActionPerformed
        Studenti s = new Studenti(G); // Create Corsi object
        s.setVisible(true);
    }//GEN-LAST:event_ModificaStudentiActionPerformed

    private void ModificaAppelliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaAppelliActionPerformed
        Appelli a = new Appelli(G); // Create Corsi object
        a.setVisible(true);
    }//GEN-LAST:event_ModificaAppelliActionPerformed

    private void ModificaIscrizioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaIscrizioniActionPerformed
        IscrizioneAppello i = new IscrizioneAppello(G); // Create Corsi object
        i.setVisible(true);
    }//GEN-LAST:event_ModificaIscrizioniActionPerformed

    private void VisualizzaIscrizioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizzaIscrizioniActionPerformed
        this.TextView.setText(G.visualizzaIscrizioni());
    }//GEN-LAST:event_VisualizzaIscrizioniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        StartPage.G.letturaCorsi("corsi.csv");
        StartPage.G.letturaDiscipline("discipline.csv");
        StartPage.G.letturaDocenti("docenti.csv");
        StartPage.G.letturaStudenti("studenti.csv");
        StartPage.G.letturaAppelli("appelli.csv");
        StartPage.G.letturaIscrizioni("iscrizioni.csv");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ModificaAppelli;
    private javax.swing.JMenuItem ModificaCorsi;
    private javax.swing.JMenuItem ModificaDiscipline;
    private javax.swing.JMenuItem ModificaDocenti;
    private javax.swing.JMenuItem ModificaIscrizioni;
    private javax.swing.JMenuItem ModificaStudenti;
    private javax.swing.JMenuBar Navigation;
    private javax.swing.JTextPane TextView;
    private javax.swing.JMenuItem VisualizzaAppelli;
    private javax.swing.JMenuItem VisualizzaCorsi;
    private javax.swing.JMenuItem VisualizzaDiscipline;
    private javax.swing.JMenuItem VisualizzaDocenti;
    private javax.swing.JMenuItem VisualizzaIscrizioni;
    private javax.swing.JMenuItem VisualizzaStudenti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
